# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imagePullPolicy: IfNotPresent

services:
  bonus-service:
    name: bonus-service
    container: bonus-service:latest
    replicaCount: 1
    env:
      DB_DSN: "host=bonusdb user=postgres password=password dbname=bonus_db port=5432"
    publishUrl: /bonus-service-direct
    port: 8050
    targetPort: 8050

  flight-service:
    name: flight-service
    container: flight-service:latest
    replicaCount: 1
    env:
      DB_DSN: "host=flightdb user=postgres password=password dbname=flight_db port=5432"
    publishUrl: /flight-service-direct
    port: 8060
    targetPort: 8060

  ticket-service:
    name: ticket-service
    container: ticket-service:latest
    replicaCount: 1
    env:
      DB_DSN: "host=ticketdb user=postgres password=password dbname=ticket_db port=5432"
    publishUrl: /ticket-service-direct
    port: 8070
    targetPort: 8070

  auth-service:
    name: auth-service
    container: auth-service:latest
    replicaCount: 1
    env:
      DB_DSN: "host=authdb user=postgres password=password dbname=auth_db port=5432"
    publishUrl: /auth
    port: 8888
    targetPort: 8888

  statistics-service:
    name: statistics-service
    container: statistics-service:latest
    replicaCount: 1
    env:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      DB_DSN: "host=statisticsdb user=postgres password=password dbname=statistics_db port=5432"
    publishUrl: /statistics
    port: 8090
    targetPort: 8090

  consumer-service:
    name: consumer-service
    container: consumer-service:latest
    replicaCount: 1
    env:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_GROUP_ID: "my-group"
      DB_DSN: "host=statisticsdb user=postgres password=password dbname=statistics_db port=5432"
    publishUrl: ""
    port: 0
    targetPort: 0

  gateway-service:
    type: NodePort
    name: gateway-service
    container: gateway-service:latest
    replicaCount: 1
    env:
      BONUS_SERVICE_URL: "http://bonus-service:8050/api/v1/"
      FLIGHT_SERVICE_URL: "http://flight-service:8060/api/v1/"
      TICKET_SERVICE_URL: "http://ticket-service:8070/api/v1/"
      AUTH_SERVICE_URL: "http://auth-service:8888/"
      STATISTICS_SERVICE_URL: "http://statistics-service:8090/"
    publishUrl: /api
    port: 8080
    targetPort: 8080

  dips-client:
    type: NodePort
    name: dips-client
    container: dips-client:latest
    replicaCount: 1
    env: {}
    publishUrl: /
    port: 80
    targetPort: 80

  zookeeper:
    name: zookeeper
    container: confluentinc/cp-zookeeper:latest
    replicaCount: 1
    env:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    publishUrl: ""
    port: 2181
    targetPort: 2181

  kafka:
    name: kafka-broker
    container: confluentinc/cp-kafka:7.3.2
    replicaCount: 1
    env:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
    publishUrl: ""
    port: 29092
    targetPort: 29092
