version: '3.1'

services:
  bonusdb:
    image: postgres:16-alpine
    container_name: bonusdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESDB=bonusdb
    volumes:
      - pg_data_bonus:/var/lib/postgresql/data
      - ./bonus_service/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  flightdb:
    image: postgres:16-alpine
    container_name: flightdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESDB=flightdb
    volumes:
      - pg_data_flight:/var/lib/postgresql/data
      - ./flight_service/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  ticketdb:
    image: postgres:16-alpine
    container_name: ticketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESDB=ticketdb
    volumes:
      - pg_data_ticket:/var/lib/postgresql/data
      - ./ticket_service/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  authdb:
    image: postgres:16-alpine
    container_name: authdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESDB=authdb
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
      - ./auth_service/sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  statisticsdb:
    image: postgres:16-alpine
    container_name: statisticsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESDB=statisticsdb
    volumes:
      - pg_data_statistics:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 15s
      retries: 10

  bonus-service:
    image: bonus-service
    container_name: bonus-service
    build:
      context: "."
      dockerfile: ./docker/bonus.Dockerfile
    ports:
      - "8050:8050"
    networks:
      - default
    depends_on:
      bonusdb:
        condition: service_healthy

  flight-service:
    image: flight-service
    container_name: flight-service
    build:
      context: "."
      dockerfile: ./docker/flight.Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      flightdb:
        condition: service_healthy

  ticket-service:
    image: ticket-service
    container_name: ticket-service
    build:
      context: "."
      dockerfile: ./docker/ticket.Dockerfile
    ports:
      - "8070:8070"
    networks:
      - default
    depends_on:
      ticketdb:
        condition: service_healthy

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: "."
      dockerfile: ./docker/auth.Dockerfile
    ports:
      - "8888:8888"
    networks:
      - default
    depends_on:
      authdb:
        condition: service_healthy

  gateway-service:
    image: gateway-service
    container_name: gateway-service
    build:
      context: "."
      dockerfile: ./docker/gateway.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    restart: "no"
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    healthcheck:
      test: ["CMD-SHELL", "ls"]
      interval: 2s
      timeout: 2s
      retries: 5

  statistics-service:
    image: statistics-service
    container_name: statistics-service
    build:
      context: "."
      dockerfile: ./docker/statistics.Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
    ports:
      - "8090:8090"
    networks:
      - default
    depends_on:
      statisticsdb:
        condition: service_healthy
      kafka:
        condition: service_healthy

  consumer-service:
    image: consumer-service
    container_name: consumer-service
    build:
      context: "."
      dockerfile: ./docker/consumer.Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
      - KAFKA_GROUP_ID=my-group
    networks:
      - default
    depends_on:
      statisticsdb:
        condition: service_healthy
      kafka:
        condition: service_healthy

volumes:
  pg_data_bonus:
    driver: local
  pg_data_flight:
    driver: local
  pg_data_ticket:
    driver: local
  pg_data_auth:
    driver: local
  pg_data_statistics:
    driver: local

networks:
  default:
