version: 16
port: 5432

defaultdb:
  user: postgres
  password: password

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

services:
  bonusdb:
    name: bonusdb
    replicaCount: 1
    hostPort: 5432
  flightdb:
    name: flightdb
    replicaCount: 1
    hostPort: 5433
  ticketdb:
    name: ticketdb
    replicaCount: 1
    hostPort: 5434
  authdb:
    name: authdb
    replicaCount: 1
    hostPort: 5435
  statisticsdb:
    name: statisticsdb
    replicaCount: 1
    hostPort: 5436