version: 16
port: 5432

default_database:
  user: postgres
  password: password

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

replicaCount: 1

services:
  bonusdb:
    name: bonusdb
    db_name: bonus_db
    replicaCount: 1
    hostPort: 5432
  flightdb:
    name: flightdb
    db_name: flight_db
    replicaCount: 1
    hostPort: 5433
  ticketdb:
    name: ticketdb
    db_name: ticket_db
    replicaCount: 1
    hostPort: 5434
  authdb:
    name: authdb
    db_name: auth_db
    replicaCount: 1
    hostPort: 5435
  statisticsdb:
    name: statisticsdb
    db_name: statistics_db
    replicaCount: 1
    hostPort: 5436