{{- range $key, $val := .Values.services }}
{{- if gt (int $val.port) 0 }}
{{- template "service.template" (dict "ctx" $ "service" $val) }}
---
{{- end }}
{{- template "deployment.template" (dict "ctx" $ "service" $val "services" $.Values.services) }}
---
{{- end }}